version: '3'
services:
  app-a:
    build:
      context: ./app-a
      dockerfile: Dockerfile
    ports:
      - "8081"
    environment:
      - PORT=8081

  app-b:
    build:
      context: ./app-b
      dockerfile: Dockerfile
    ports:
      - "8082"
    environment:
      - PORT=8082
    depends_on:
      - app-a

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app-a
      - app-b

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379"